import 'package:flutter/foundation.dart';
import './models/glasses_frame.dart';

var Dummy_Data = [
  GlassesFrame(
    id: 1,
    noModel: 'CARRERINO68',
    noColor: '807',
    price: 427,
    frameType: 'plastic',
    size: 50,
    arm: 135,
    bridge: 16,
    frameshape: FrameShape.Square,
    frameClass: FrameClass.Child,
    manufactureCompany: 'CARRERA',
    imageUrl: [
      'assets/product/child/1/1.jpg',
      'assets/product/child/1/2.jpg',
      'assets/product/child/1/3.jpg',
    ],
  ),
  GlassesFrame(
    id: 2,
    noModel: '5002',
    noColor: '41',
    price: 174,
    frameType: 'ACETATE',
    size: 43,
    arm: 115,
    bridge: 18,
    frameshape: FrameShape.Circular,
    frameClass: FrameClass.Child,
    manufactureCompany: 'OEX',
    imageUrl: [
      'assets/product/child/2/1.jpg',
      'assets/product/child/2/2.jpg',
    ],
  ),
  GlassesFrame(
    id: 3,
    noModel: '5004',
    noColor: '33',
    price: 174,
    frameType: 'ACETATE',
    size: 42,
    arm: 115,
    bridge: 17,
    frameshape: FrameShape.Rectangular,
    frameClass: FrameClass.Child,
    manufactureCompany: 'OEX',
    imageUrl: [
      'assets/product/child/3/1.jpg',
      'assets/product/child/3/2.jpg',
    ],
  ),
  GlassesFrame(
    id: 4,
    noModel: '7010',
    noColor: '6',
    price: 174,
    frameType: 'plastic',
    size: 46,
    arm: 136,
    bridge: 21,
    frameshape: FrameShape.Circular,
    frameClass: FrameClass.Child,
    manufactureCompany: 'OEX',
    imageUrl: [
      'assets/product/child/4/1.jpg',
      'assets/product/child/4/2.jpg',
    ],
  ),
  GlassesFrame(
    id: 5,
    noModel: '5003',
    noColor: '14',
    price: 174,
    frameType: 'ACETATE',
    size: 44,
    arm: 115,
    bridge: 17,
    frameshape: FrameShape.Rectangular,
    frameClass: FrameClass.Child,
    manufactureCompany: 'OEX',
    imageUrl: [
      'assets/product/child/5/1.jpg',
      'assets/product/child/5/2.jpg',
    ],
  ),
  GlassesFrame(
    id: 6,
    noModel: '245',
    noColor: 'J5G',
    price: 984,
    frameType: 'Metal',
    size: 50,
    arm: 140,
    bridge: 22,
    frameshape: FrameShape.Circular,
    frameClass: FrameClass.Man,
    manufactureCompany: 'CARRERA',
    imageUrl: [
      'assets/product/men/1/1.jpg',
      'assets/product/men/1/2.jpg',
      'assets/product/men/1/3.jpg',
    ],
  ),
  GlassesFrame(
    id: 7,
    noModel: '1066',
    noColor: 'BLX',
    price: 949,
    frameType: 'Metal&plastic',
    size: 55,
    arm: 145,
    bridge: 19,
    frameshape: FrameShape.Rectangular,
    frameClass: FrameClass.Man,
    manufactureCompany: 'BOSS',
    imageUrl: [
      'assets/product/men/2/1.jpg',
      'assets/product/men/2/2.jpg',
      'assets/product/men/2/3.jpg',
    ],
  ),
  GlassesFrame(
    id: 8,
    noModel: 'PLDD363G',
    noColor: 'YL718',
    price: 347,
    frameType: 'من الأمام بلاستيك ،الأذرعة معدني',
    size: 50,
    arm: 145,
    bridge: 18,
    frameshape: FrameShape.Square,
    frameClass: FrameClass.Man,
    manufactureCompany: 'POLAROID',
    imageUrl: [
      'assets/product/men/3/1.jpg',
      'assets/product/men/3/2.jpg',
      'assets/product/men/3/3.jpg',
      'assets/product/men/3/4.jpg',
    ],
  ),
  GlassesFrame(
    id: 9,
    noModel: '1096',
    noColor: 'FLL',
    price: 1260,
    frameType: 'METAL',
    size: 54,
    arm: 145,
    bridge: 18,
    frameshape: FrameShape.Square,
    frameClass: FrameClass.Man,
    manufactureCompany: 'HUGO',
    imageUrl: [
      'assets/product/men/4/1.jpg',
      'assets/product/men/4/2.jpg',
    ],
  ),
  GlassesFrame(
    id: 10,
    noModel: 'CA2010T',
    noColor: 'J5G',
    price: 656,
    frameType: 'METAL',
    size: 51,
    arm: 135,
    bridge: 19,
    frameshape: FrameShape.Square,
    frameClass: FrameClass.Man,
    manufactureCompany: 'CARRERA',
    imageUrl: [
      'assets/product/men/5/1.jpg',
      'assets/product/men/5/2.jpg',
      'assets/product/men/5/3.jpg',
    ],
  ),
  GlassesFrame(
    id: 11,
    noModel: 'MK3048',
    noColor: '1108',
    price: 876,
    frameType: 'METAL',
    size: 54,
    arm: 140,
    bridge: 17,
    frameshape: FrameShape.Oval,
    frameClass: FrameClass.Woman,
    manufactureCompany: 'CARRERA',
    imageUrl: [
      'assets/product/women/1/1.jpg',
      'assets/product/women/1/2.jpg',
      'assets/product/women/1/3.jpg',
    ],
  ),
  GlassesFrame(
    id: 12,
    noModel: 'PLDD363G',
    noColor: 'YL718',
    price: 347,
    frameType: 'من الأمام بلاستيك ،الأذرعة معدني',
    size: 50,
    arm: 145,
    bridge: 18,
    frameshape: FrameShape.Square,
    frameClass: FrameClass.Woman,
    manufactureCompany: 'POLARIOD',
    imageUrl: [
      'assets/product/women/2/1.jpg',
      'assets/product/women/2/2.jpg',
      'assets/product/women/2/3.jpg',
      'assets/product/women/2/4.jpg',
    ],
  ),
  GlassesFrame(
    id: 13,
    noModel: 'DG3335',
    noColor: '502',
    price: 1236,
    frameType: 'plastic',
    size: 54,
    arm: 145,
    bridge: 19,
    frameshape: FrameShape.Oval,
    frameClass: FrameClass.Woman,
    manufactureCompany: 'DOLCE &GABBANA',
    imageUrl: [
      'assets/product/women/3/1.jpg',
      'assets/product/women/3/2.jpg',
      'assets/product/women/3/3.jpg',
    ],
  ),
  GlassesFrame(
    id: 14,
    noModel: 'TH1684',
    noColor: '2M216',
    price: 839,
    frameType: 'METAL',
    size: 54,
    arm: 140,
    bridge: 16,
    frameshape: FrameShape.Rectangular,
    frameClass: FrameClass.Woman,
    manufactureCompany: 'TOMMY HILFGER',
    imageUrl: [
      'assets/product/women/4/1.jpg',
      'assets/product/women/4/2.jpg',
      'assets/product/women/4/3.jpg',
    ],
  ),
  GlassesFrame(
    id: 15,
    noModel: 'EA1118',
    noColor: '3011',
    price: 854,
    frameType: 'METAL',
    size: 51,
    arm: 140,
    bridge: 18,
    frameshape: FrameShape.Circular,
    frameClass: FrameClass.Woman,
    manufactureCompany: 'EMPORIO ARMANI',
    imageUrl: [
      'assets/product/women/5/1.jpg',
      'assets/product/women/5/2.jpg',
      'assets/product/women/5/3.jpg',
    ],
  ),
];
